#include <time.h>
#include <stdlib.h>
#include <stdio.h>

#include "./index.h"

int get_random_int()
{
	// Seed the random number generator
	// `srand` is used to set the seed for the random number generator used by `rand`
	// `time(0)` returns the current time in seconds since the Unix epoch
	// The seed is set to the current time, so the random number generator will produce different numbers each time the program is run
	// seed here means the starting point of the random number generator
	srand(time(0));

	// Generate a random number
	// `rand` generates a pseudo-random number between 0 and `RAND_MAX`
	// `RAND_MAX` is a constant defined in `stdlib.h` that represents the maximum value returned by `rand`
	// Don't use this function for security purposes, as it's not cryptographically secure
	// Because the seed is set to the current time, the random number generated will be different each time the program is run
	// While this is useful for generating random numbers in a program, it's not suitable for cryptographic purposes
	// Because the sequence of numbers generated by `rand` is deterministic, it's not suitable for cryptographic purposes
	// And determining the seed can allow an attacker to predict the random numbers generated
	// For cryptographic purposes, use a library like OpenSSL
	// Which provides secure random number generation functions
	return rand();
}

void test_get_random_int()
{

	printf("Testing get_random_int\n");
	int random_int = get_random_int();
	printf("Random int: %d\n", random_int);
}